import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronLeft, ChevronRight, CircleHelp, Disc3, FileText, Headphones, Library, LoaderCircle, Mic, MicOff, MoonStar, Music2, Pause, Play, Plus, RotateCcw, Sparkles, Upload, Volume2, VolumeX, WandSparkles, X } from 'lucide-react';
import { type ChangeEvent, type DragEvent, type FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { api, assetUrl, uploadPdf } from './api';
import { useStoryStore } from './store';
import type { BriefStory, InputMode, LibraryEntry, RenderedStory, StoryScript } from './types';

type SpeechRecognitionLike = { continuous: boolean; interimResults: boolean; lang: string; start(): void; stop(): void; onresult: ((event: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null; onend: (() => void) | null; onerror: (() => void) | null; };
type SpeechRecognitionConstructor = new () => SpeechRecognitionLike;
declare global { interface Window { SpeechRecognition?: SpeechRecognitionConstructor; webkitSpeechRecognition?: SpeechRecognitionConstructor; } }

const modes: Array<{ id: InputMode; title: string; eyebrow: string; description: string; icon: typeof Mic; className: string }> = [
  { id: 'raw_story', title: 'Raw Story', eyebrow: 'FROM YOUR WORLD', description: 'Tell us the spark. Type it, speak it, or drop in a PDF.', icon: Mic, className: 'mode-raw' },
  { id: 'existing_book', title: 'Existing Novel', eyebrow: 'A FRESH LISTEN', description: 'Bring a book you love. We’ll shape a respectful, original audio brief.', icon: BookOpen, className: 'mode-book' },
  { id: 'dreamcast', title: 'DreamCast', eyebrow: 'FROM AFTER MIDNIGHT', description: 'Turn the strange, beautiful logic of your dream into cinema for the ears.', icon: MoonStar, className: 'mode-dream' }
];

function App() {
  return <AnimatePresence mode="wait"><Routes>
    <Route path="/" element={<Landing />} /><Route path="/create/:mode" element={<InputScreen />} /><Route path="/review" element={<Review />} />
    <Route path="/directing" element={<Directing />} /><Route path="/player" element={<Player />} /><Route path="/library" element={<LibraryPage />} />
    <Route path="*" element={<Navigate to="/" replace />} />
  </Routes></AnimatePresence>;
}

function Page({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <motion.main className={`page ${className}`} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.35 }}>{children}</motion.main>;
}
function Nav({ dark = false }: { dark?: boolean }) {
  return <nav className={`nav ${dark ? 'nav-dark' : ''}`}><Link to="/" className="brand" aria-label="Audiora home"><span className="brand-mark"><Disc3 size={17} /></span>AUDIORA</Link><div className="nav-actions"><Link to="/library" className="nav-link"><Library size={17} /> My stories</Link></div></nav>;
}
function Landing() {
  return <Page className="landing"><Nav dark /><div className="orb orb-a" /><div className="orb orb-b" />
    <section className="landing-hero"><motion.p className="eyebrow" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>STORIES, HEARD DIFFERENTLY</motion.p>
      <h1>Close your eyes.<br /><span>See everything.</span></h1><p className="hero-copy">Give Audiora a fragment, a favorite book, or a dream. We turn it into a cinematic world with voices, score, and atmosphere.</p>
      <div className="signal-line"><span /> your idea, in surround sound <span /></div>
    </section>
    <section className="mode-grid" aria-label="Choose a story input mode">{modes.map((mode, index) => { const Icon = mode.icon; return <motion.div key={mode.id} initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .18 + index * .09 }}><Link className={`mode-card ${mode.className}`} to={`/create/${mode.id}`}><div className="mode-visual"><Icon size={30} strokeWidth={1.55} /><span className="card-number">0{index + 1}</span></div><p className="eyebrow">{mode.eyebrow}</p><h2>{mode.title}</h2><p>{mode.description}</p><span className="card-arrow" aria-hidden="true"><ArrowRight size={18} /></span></Link></motion.div>; })}</section>
    <p className="landing-footnote"><Headphones size={15} /> best experienced with headphones</p>
  </Page>;
}

function VoiceCapture({ onTranscript, dream }: { onTranscript: (text: string) => void; dream?: boolean }) {
  const [recording, setRecording] = useState(false); const [supported] = useState(() => Boolean(window.SpeechRecognition || window.webkitSpeechRecognition)); const recognition = useRef<SpeechRecognitionLike | null>(null);
  const toggle = () => {
    if (!supported) return;
    if (recording) { recognition.current?.stop(); return; }
    const Recognition = window.SpeechRecognition ?? window.webkitSpeechRecognition; if (!Recognition) return;
    const next = new Recognition(); next.continuous = true; next.interimResults = true; next.lang = 'en-US';
    next.onresult = (event) => { let text = ''; for (let index = 0; index < event.results.length; index++) text += event.results[index][0].transcript; onTranscript(text.trim()); };
    next.onend = () => setRecording(false); next.onerror = () => setRecording(false); recognition.current = next; next.start(); setRecording(true);
  };
  return <div className={`voice-capture ${recording ? 'is-recording' : ''} ${dream ? 'dream-voice' : ''}`}><button type="button" onClick={toggle} className="mic-button" aria-label={recording ? 'Stop voice recording' : 'Start voice recording'} disabled={!supported}>{recording ? <MicOff size={24} /> : <Mic size={24} />}</button><div><strong>{recording ? 'Listening… speak freely' : supported ? 'Add your voice' : 'Voice capture unavailable in this browser'}</strong><p>{recording ? <span className="levels"><i /><i /><i /><i /><i /></span> : 'Your words appear in the story notes below.'}</p></div>{recording && <button type="button" className="text-button" onClick={toggle}>Done</button>}</div>;
}

function InputScreen() {
  const { mode: rawMode } = useParams(); const mode = rawMode as InputMode; const navigate = useNavigate(); const setMode = useStoryStore((state) => state.setMode); const setBrief = useStoryStore((state) => state.setBrief);
  const detail = modes.find((item) => item.id === mode); const [text, setText] = useState(''); const [transcript, setTranscript] = useState(''); const [pdfText, setPdfText] = useState(''); const [title, setTitle] = useState(''); const [author, setAuthor] = useState(''); const [busy, setBusy] = useState(false); const [pdfBusy, setPdfBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (detail) setMode(mode); }, [detail, mode, setMode]);
  if (!detail) return <Navigate to="/" replace />;
  const hasInput = mode === 'existing_book' ? Boolean(title.trim()) : Boolean(text.trim() || transcript.trim() || pdfText.trim());
  const handlePdf = async (file?: File) => { if (!file) return; setPdfBusy(true); setError(''); try { const result = await uploadPdf(file); setPdfText(result.pdfText); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not extract the PDF.'); } finally { setPdfBusy(false); } };
  const onDrop = (event: DragEvent<HTMLLabelElement>) => { event.preventDefault(); void handlePdf(event.dataTransfer.files[0]); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!hasInput) return; setBusy(true); setError(''); try { const payload = mode === 'existing_book' ? { mode, title, author: author || null } : mode === 'raw_story' ? { mode, text: text || null, audioTranscript: transcript || null, pdfText: pdfText || null } : { mode, text: text || null, audioTranscript: transcript || null }; const brief = await api<BriefStory>('/api/story/generate-brief', { method: 'POST', body: JSON.stringify(payload) }); setBrief(brief); navigate('/review'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not generate a story brief.'); } finally { setBusy(false); } };
  const isDream = mode === 'dreamcast';
  return <Page className={`create-page ${isDream ? 'dream-page' : ''}`}><Nav dark={isDream} /><section className="input-shell"><Link to="/" className="back-link"><ArrowLeft size={16} /> Change mode</Link><div className="input-heading"><p className="eyebrow">{detail.eyebrow}</p><h1>{mode === 'raw_story' ? 'What happened?' : mode === 'existing_book' ? 'Which book is calling?' : 'Tell us what you saw.'}</h1><p>{mode === 'raw_story' ? 'Messy notes are welcome. We’ll find the narrative shape.' : mode === 'existing_book' ? 'We’ll create a fresh, listener-friendly brief—never a copied excerpt.' : 'The impossible details are usually the important ones.'}</p></div>
    <form onSubmit={submit} className="input-form">
      {mode === 'existing_book' ? <><label className="field-label">Book title<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. The Left Hand of Darkness" maxLength={160} /></label><label className="field-label">Author <span>(optional)</span><input value={author} onChange={(event) => setAuthor(event.target.value)} placeholder="e.g. Ursula K. Le Guin" maxLength={120} /></label><div className="book-suggestions"><span>Try a spark</span><button type="button" onClick={() => { setTitle('The Night Circus'); setAuthor('Erin Morgenstern'); }}>The Night Circus</button><button type="button" onClick={() => { setTitle('Piranesi'); setAuthor('Susanna Clarke'); }}>Piranesi</button></div></> : <><label className="field-label">{isDream ? 'Dream notes' : 'Story notes'}<textarea autoFocus value={text} onChange={(event) => setText(event.target.value)} placeholder={isDream ? 'I was walking through a flooded library. The books were breathing…' : 'There was a train platform, a missed call, and a promise I could not forget…'} /></label><VoiceCapture dream={isDream} onTranscript={setTranscript} />{transcript && <div className="transcript-preview"><span>LIVE TRANSCRIPT</span><button type="button" aria-label="Clear transcript" onClick={() => setTranscript('')}><X size={14} /></button><p>{transcript}</p></div>}{mode === 'raw_story' && <><label className={`pdf-drop ${pdfBusy ? 'is-busy' : ''}`} onDragOver={(event) => event.preventDefault()} onDrop={onDrop}><input type="file" accept="application/pdf" onChange={(event: ChangeEvent<HTMLInputElement>) => void handlePdf(event.target.files?.[0])} /><div className="upload-icon">{pdfBusy ? <LoaderCircle className="spin" size={20} /> : <Upload size={20} />}</div><div><strong>{pdfBusy ? 'Extracting your PDF…' : 'Drop in a story PDF'}</strong><p>or choose a file · text-based PDFs up to 10 MB</p></div></label>{pdfText && <label className="field-label extracted-label">Extracted pages <span>edit before generating</span><textarea value={pdfText} onChange={(event) => setPdfText(event.target.value)} /></label>}</>}</>}
      {error && <div className="inline-error" role="alert">{error}<button type="button" onClick={() => setError('')}>Dismiss</button></div>}
      <button className="primary-button" disabled={!hasInput || busy} type="submit">{busy ? <><LoaderCircle className="spin" size={18} /> Finding the story…</> : <><WandSparkles size={18} /> Generate my story <ArrowRight size={17} /></>}</button><p className="form-help">{hasInput ? 'Your source stays yours. Audiora creates a new narratable brief.' : 'Add a little something to unlock your story.'}</p>
    </form></section></Page>;
}

function Review() {
  const navigate = useNavigate(); const brief = useStoryStore((state) => state.brief); const setBrief = useStoryStore((state) => state.setBrief); const [edit, setEdit] = useState<BriefStory | null>(brief); if (!brief || !edit) return <Navigate to="/" replace />;
  return <Page className="review-page"><Nav /><section className="review-shell"><div className="review-top"><Link to="/" className="back-link"><ArrowLeft size={16} /> Start over</Link><div className="review-status"><Check size={15} /> Story brief ready</div></div><div className="review-title-row"><input aria-label="Story title" value={edit.suggestedTitle} onChange={(event) => setEdit({ ...edit, suggestedTitle: event.target.value })} /><input aria-label="Story genre" className="genre-editor" value={edit.suggestedGenre} onChange={(event) => setEdit({ ...edit, suggestedGenre: event.target.value })} /></div><p className="review-intro">Read it like a listener. This is the moment to tune the words before the cast comes in.</p><textarea className="story-editor" aria-label="Editable story brief" value={edit.briefStory} onChange={(event) => setEdit({ ...edit, briefStory: event.target.value })} /><div className="review-actions"><button className="secondary-button" onClick={() => navigate('/create/raw_story')}><RotateCcw size={17} /> Regenerate</button><button className="primary-button" onClick={() => { setBrief(edit); navigate('/directing'); }} disabled={edit.briefStory.trim().length < 30}><Sparkles size={18} /> Sounds good, continue <ArrowRight size={17} /></button></div></section></Page>;
}

const progressStages = ['Casting characters…', 'Blocking each scene…', 'Scoring the emotional turns…', 'Layering ambience…', 'Mixing your story…'];
function Directing() {
  const navigate = useNavigate(); const brief = useStoryStore((state) => state.brief); const setRendered = useStoryStore((state) => state.setRendered); const [stage, setStage] = useState(0); const [error, setError] = useState(''); const [attempt, setAttempt] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setStage((current) => Math.min(current + 1, progressStages.length - 1)), 1350); return () => window.clearInterval(timer); }, [attempt]);
  useEffect(() => { if (!brief) return; let alive = true; const run = async () => { setError(''); setStage(0); try { const script = await api<StoryScript>('/api/story/build-script', { method: 'POST', body: JSON.stringify({ briefStory: brief.briefStory, title: brief.suggestedTitle, genre: brief.suggestedGenre }) }); if (!alive) return; setStage(3); const rendered = await api<RenderedStory>('/api/story/render-audio', { method: 'POST', body: JSON.stringify(script) }); if (!alive) return; setRendered(rendered); navigate('/player'); } catch (cause) { if (alive) setError(cause instanceof Error ? cause.message : 'The studio lost its signal.'); } }; void run(); return () => { alive = false; }; }, [attempt, brief, navigate, setRendered]);
  if (!brief) return <Navigate to="/" replace />;
  return <Page className="directing-page"><div className="director-glow" /><Nav dark /><section className="director-content">{error ? <div className="process-error"><CircleHelp size={30} /><h1>We hit a rough cut.</h1><p>{error}</p><button className="primary-button" onClick={() => setAttempt((value) => value + 1)}><RotateCcw size={17} /> Try again</button></div> : <><div className="director-disc"><span /><Music2 size={48} /><i /></div><p className="eyebrow">AUDIORA STUDIO</p><h1>{progressStages[stage]}</h1><p>We’re turning <strong>{brief.suggestedTitle}</strong> into a world you can step into.</p><div className="stage-list">{progressStages.map((item, index) => <div key={item} className={index <= stage ? 'active' : ''}><span>{index < stage ? <Check size={13} /> : index + 1}</span>{item}</div>)}</div></>}</section></Page>;
}

function formatTime(value: number) { if (!Number.isFinite(value)) return '0:00'; return `${Math.floor(value / 60)}:${String(Math.floor(value % 60)).padStart(2, '0')}`; }
function Player() {
  const rendered = useStoryStore((state) => state.rendered); const [playing, setPlaying] = useState(false); const [time, setTime] = useState(0); const [duration, setDuration] = useState(rendered?.audio.duration_seconds ?? 0); const [volume, setVolume] = useState(.82); const audioRef = useRef<HTMLAudioElement>(null);
  if (!rendered) return <Navigate to="/library" replace />;
  const { script, audio, coverImageUrl } = rendered; const currentSceneIndex = Math.max(0, audio.scene_markers.findIndex((marker) => time >= marker.start_seconds && time < marker.end_seconds)); const currentScene = script.scenes[currentSceneIndex] ?? script.scenes[0];
  const toggle = async () => { const player = audioRef.current; if (!player) return; if (playing) { player.pause(); setPlaying(false); } else { try { await player.play(); setPlaying(true); } catch { setPlaying(false); } } };
  const seek = (value: number) => { if (audioRef.current) audioRef.current.currentTime = value; setTime(value); };
  const jump = (delta: number) => { const index = Math.max(0, Math.min(audio.scene_markers.length - 1, currentSceneIndex + delta)); seek(audio.scene_markers[index].start_seconds); };
  return <Page className="player-page"><div className="player-background" style={{ backgroundImage: `url(${assetUrl(coverImageUrl)})` }} /><div className="player-shade" /><Nav dark /><audio ref={audioRef} src={assetUrl(audio.audio_url)} preload="metadata" onTimeUpdate={(event) => setTime(event.currentTarget.currentTime)} onLoadedMetadata={(event) => setDuration(event.currentTarget.duration || audio.duration_seconds)} onEnded={() => setPlaying(false)} onVolumeChange={(event) => setVolume(event.currentTarget.volume)} />
    <section className="player-layout"><div className="now-playing"><div className="cover-wrap"><img className="cover" src={assetUrl(coverImageUrl)} alt={`Cover artwork for ${script.title}`} /><div className="cover-glint" /></div><div className="track-copy"><p className="eyebrow">NOW PLAYING</p><h1>{script.title}</h1><span className="genre-pill">{script.genre}</span><p className="scene-status">SCENE {currentSceneIndex + 1} <i /> {currentScene?.title}</p><div className={`visualizer ${playing ? 'playing' : ''}`} aria-hidden="true">{Array.from({ length: 28 }, (_, index) => <i key={index} style={{ animationDelay: `${index * -0.08}s`, height: `${18 + (index * 17) % 62}%` }} />)}</div></div></div>
      <div className="player-controls"><div className="time-row"><span>{formatTime(time)}</span><div className="scrubber"><input aria-label="Seek through story" type="range" min="0" max={duration || 1} step=".1" value={Math.min(time, duration || 1)} onChange={(event) => seek(Number(event.target.value))} />{audio.scene_markers.map((marker) => <button key={marker.scene_id} className="scene-marker" aria-label={`Go to scene ${marker.scene_id}`} style={{ left: `${(marker.start_seconds / duration) * 100}%` }} onClick={() => seek(marker.start_seconds)} />)}</div><span>{formatTime(Math.max(0, duration - time))}</span></div><div className="control-row"><button onClick={() => jump(-1)} aria-label="Previous scene"><ChevronLeft size={27} /></button><button className="play-button" onClick={toggle} aria-label={playing ? 'Pause story' : 'Play story'}>{playing ? <Pause fill="currentColor" size={25} /> : <Play fill="currentColor" size={25} />}</button><button onClick={() => jump(1)} aria-label="Next scene"><ChevronRight size={27} /></button><div className="volume"><button onClick={() => { if (audioRef.current) audioRef.current.volume = volume ? 0 : .82; }} aria-label={volume ? 'Mute' : 'Unmute'}>{volume ? <Volume2 size={18} /> : <VolumeX size={18} />}</button><input aria-label="Volume" type="range" min="0" max="1" step=".02" value={volume} onChange={(event) => { const value = Number(event.target.value); if (audioRef.current) audioRef.current.volume = value; setVolume(value); }} /></div></div></div>
      <aside className="scene-panel"><div className="scene-panel-head"><span>CHAPTERS</span><b>{script.scenes.length} scenes</b></div>{script.scenes.map((scene, index) => <button key={scene.scene_id} className={`scene-row ${index === currentSceneIndex ? 'current' : ''}`} onClick={() => seek(audio.scene_markers[index]?.start_seconds ?? 0)}><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{scene.title}</strong><p>{scene.description}</p></div>{index === currentSceneIndex && <Play size={13} fill="currentColor" />}</button>)}</aside></section></Page>;
}

function LibraryPage() {
  const navigate = useNavigate(); const setRendered = useStoryStore((state) => state.setRendered); const [entries, setEntries] = useState<LibraryEntry[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setEntries(await api<LibraryEntry[]>('/api/library')); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load your library.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <Page className="library-page"><Nav /><section className="library-shell"><div className="library-heading"><div><p className="eyebrow">YOUR LISTENING ROOM</p><h1>My stories</h1><p>Every world you’ve directed, ready when you are.</p></div><Link className="primary-button" to="/"><Plus size={17} /> New story</Link></div>{loading ? <div className="library-state"><LoaderCircle className="spin" /> Loading your stories…</div> : error ? <div className="library-state"><CircleHelp /> {error}<button className="secondary-button" onClick={() => void load()}>Retry</button></div> : entries.length ? <div className="library-grid">{entries.map((entry) => <button className="library-card" key={entry.id} onClick={() => { setRendered(entry.rendered); navigate('/player'); }}><img src={assetUrl(entry.coverImageUrl)} alt="" /><span className="library-card-play"><Play fill="currentColor" size={17} /></span><p>{entry.genre}</p><h2>{entry.title}</h2><small>{new Date(entry.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</small></button>)}</div> : <div className="library-empty"><Music2 size={37} /><h2>The room is quiet—for now.</h2><p>Your finished stories will collect here.</p><Link to="/" className="secondary-button">Create your first story</Link></div>}</section></Page>;
}

export default App;
